### ISSUE TITLE
on max-zoom, double click zooms out.

### ISSUE THREAD

**Issue by matthewfdaniels** [jessp/book_covers#34]

**Comment by jessp** [comment]
Could you clarify where you see this behaviour/what factors are involved?

On the current master (i.e. https://jessp.github.io/book_covers/) I can only replicate the behaviour in the Chrome mobile emulator.

Behaviour works as expected for me in desktop (Chrome, Firefox and Safari) and on my cell (Android phone, tested in Chrome and Samsung internet).

**Comment by matthewfdaniels** [comment]
actually this was from someone on the team. But I now realize that double clicking triggers the book zoom event. Let’s close this issue!
