### ISSUE TITLE
narrow down motifs to items that are most interesting.

### ISSUE THREAD

**Issue by matthewfdaniels** [jessp/book_covers#36]

**Comment by jessp** [comment]
Based on Swati's notes, and my own preferences, I'm currently considering the following 25 motifs:

Sky, Landscape, Fictional character, Illustration, History, Smile, Vehicle, Plant, Action film, Happy, Line, Canidae, Heros, Lady, Architecture, Ocean, Face, Calligraphy, Dress, City, Suit, Love, Summer, Winter, Space

These are all relatively common motifs with "Space" being the least frequently occurring  with 37 instances.
